
import java.util.Scanner;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Jason
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Question = new javax.swing.JLabel();
        westindo = new javax.swing.JButton();
        eastindo = new javax.swing.JButton();
        centerindo = new javax.swing.JButton();
        malay = new javax.swing.JButton();
        viet = new javax.swing.JButton();
        thai = new javax.swing.JButton();
        kamboja = new javax.swing.JButton();
        singapore = new javax.swing.JButton();
        laos = new javax.swing.JButton();
        brunei = new javax.swing.JButton();
        philip = new javax.swing.JButton();
        myanmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Question.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Question.setText("Where Are You From?");

        westindo.setText("Indonesia Barat");
        westindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                westindoActionPerformed(evt);
            }
        });

        eastindo.setText("Indonesia Timur");
        eastindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastindoActionPerformed(evt);
            }
        });

        centerindo.setText("Indonesia Tengah");
        centerindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centerindoActionPerformed(evt);
            }
        });

        malay.setText("Malaysia");
        malay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malayActionPerformed(evt);
            }
        });

        viet.setText("Vietnam");
        viet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vietActionPerformed(evt);
            }
        });

        thai.setText("Thailand");
        thai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thaiActionPerformed(evt);
            }
        });

        kamboja.setText("Kamboja");
        kamboja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kambojaActionPerformed(evt);
            }
        });

        singapore.setText("Singapore");
        singapore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singaporeActionPerformed(evt);
            }
        });

        laos.setText("Laos");
        laos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laosActionPerformed(evt);
            }
        });

        brunei.setText("Brunei Darussalam");
        brunei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bruneiActionPerformed(evt);
            }
        });

        philip.setText("Philippines");
        philip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                philipActionPerformed(evt);
            }
        });

        myanmar.setText("Myanmar");
        myanmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myanmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Question, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(westindo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(malay, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thai, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brunei, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eastindo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(singapore, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(centerindo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viet, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kamboja, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(laos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(philip, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(myanmar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Question, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(westindo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eastindo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(centerindo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(malay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viet, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(singapore, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thai, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kamboja, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brunei, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(philip, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myanmar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void westindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_westindoActionPerformed
        indowest obj = new indowest();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_westindoActionPerformed

    private void eastindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastindoActionPerformed

        indoeast obj = new indoeast();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_eastindoActionPerformed

    private void centerindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centerindoActionPerformed

        indocenter obj = new indocenter();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_centerindoActionPerformed

    private void malayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malayActionPerformed
        malaysia obj = new malaysia();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_malayActionPerformed

    private void vietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vietActionPerformed
        vietnam obj = new vietnam();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_vietActionPerformed

    private void thaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thaiActionPerformed
        thailand obj = new thailand();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_thaiActionPerformed

    private void kambojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kambojaActionPerformed
        kamboja obj = new kamboja();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_kambojaActionPerformed

    private void singaporeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singaporeActionPerformed
        singapore obj = new singapore();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_singaporeActionPerformed

    private void laosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laosActionPerformed
        laos obj = new laos();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_laosActionPerformed

    private void bruneiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bruneiActionPerformed
        brunei obj = new brunei();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bruneiActionPerformed

    private void philipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_philipActionPerformed
        philippine obj = new philippine();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_philipActionPerformed

    private void myanmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myanmarActionPerformed
        myanmar obj = new myanmar();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_myanmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Question;
    private javax.swing.JButton brunei;
    private javax.swing.JButton centerindo;
    private javax.swing.JButton eastindo;
    private javax.swing.JButton kamboja;
    private javax.swing.JButton laos;
    private javax.swing.JButton malay;
    private javax.swing.JButton myanmar;
    private javax.swing.JButton philip;
    private javax.swing.JButton singapore;
    private javax.swing.JButton thai;
    private javax.swing.JButton viet;
    private javax.swing.JButton westindo;
    // End of variables declaration//GEN-END:variables
}
